from __future__ import annotations

from app.models import OfficialAnswer, OfficialIngestResponse, OfficialSource
from app.official.corpus import OfficialCorpus
from app.official.ingestion import OfficialIngestionService
from app.official.retrieval import HybridRetriever
from app.official.vector_store import OfficialVectorStore


class OfficialEvidenceService:
    """Lightweight hybrid RAG service over the seeded official corpus."""

    def __init__(
        self,
        corpus: OfficialCorpus | None = None,
        retriever: HybridRetriever | None = None,
        vector_store: OfficialVectorStore | None = None,
        ingestion_service: OfficialIngestionService | None = None,
    ) -> None:
        self.corpus = corpus or OfficialCorpus()
        self.vector_store = vector_store or OfficialVectorStore()
        self.vector_store.upsert_chunks(self.corpus.chunks)
        self.retriever = retriever or HybridRetriever(self.corpus, self.vector_store)
        self.ingestion_service = ingestion_service or OfficialIngestionService(
            self.corpus, self.vector_store
        )

    def get_official_answer(
        self, question: str, college_name: str | None, provided: OfficialAnswer | None
    ) -> OfficialAnswer:
        if provided is not None:
            return provided

        retrieved = self.retriever.retrieve(question, college_name)
        if not retrieved:
            return OfficialAnswer(
                summary=(
                    "I could not find a matching official source in the current local corpus. "
                    "Connect the full official ingestion pipeline to answer this reliably."
                ),
                note=(
                    "The official hybrid RAG is working against the seeded corpus only. "
                    "Production use should ingest JoSAA, institute PDFs, and current admission documents."
                ),
            )

        bullet_points = [f"- {chunk.content}" for chunk in retrieved[:3]]
        college_prefix = f" for {college_name}" if college_name else ""
        summary = (
            f"Based on the highest-scoring official sources{college_prefix}, the most relevant points are:\n"
            + "\n".join(bullet_points)
        )
        sources = [
            OfficialSource(title=chunk.title, url=chunk.url, snippet=chunk.content)
            for chunk in retrieved[:4]
        ]
        return OfficialAnswer(
            summary=summary,
            sources=sources,
            note=(
                "This answer is generated by a lightweight hybrid retriever that combines lexical "
                "and vector-style similarity over the local official corpus."
            ),
            retrieved_chunks=retrieved,
        )

    async def ingest_sources(
        self,
        *,
        college_name: str,
        urls: list[str],
        file_paths: list[str],
        title: str | None = None,
        source_kind: str = "official",
    ) -> OfficialIngestResponse:
        ingested, errors = await self.ingestion_service.ingest(
            college_name=college_name,
            urls=urls,
            file_paths=file_paths,
            title=title,
            source_kind=source_kind,
        )
        self.retriever.refresh()
        return OfficialIngestResponse(ingested=ingested, errors=errors)
