// Mock data for development / demo purposes
// This allows the frontend to work without the backend running

export const EXAM_OPTIONS = [
  { value: 'JEE Main', label: 'JEE Main' },
  { value: 'JEE Advanced', label: 'JEE Advanced' },
  { value: 'BITSAT', label: 'BITSAT' },
  { value: 'MET', label: 'Manipal MET' },
  { value: 'COMEDK', label: 'COMEDK UGET' },
  { value: 'WBJEE', label: 'WBJEE' },
  { value: 'KCET', label: 'KCET' },
  { value: 'AP EAMCET', label: 'AP EAMCET' },
  { value: 'TS EAMCET', label: 'TS EAMCET' },
  { value: 'MHT CET', label: 'MHT CET' },
];

export const BRANCH_OPTIONS = [
  'Computer Science & Engineering',
  'Electronics & Communication',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Aerospace Engineering',
  'Biotechnology',
  'Mathematics & Computing',
  'Data Science & AI',
  'Information Technology',
  'Metallurgical Engineering',
  'Engineering Physics',
];

export const STATE_OPTIONS = [
  'Andhra Pradesh', 'Bihar', 'Delhi', 'Goa', 'Gujarat', 'Haryana',
  'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra',
  'Odisha', 'Punjab', 'Rajasthan', 'Tamil Nadu', 'Telangana',
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
];

export const ZONE_OPTIONS = ['North', 'South', 'East', 'West', 'Central', 'North-East'];

export const COLLEGE_NAMES = [
  'IIT Bombay', 'IIT Delhi', 'IIT Madras', 'IIT Kanpur', 'IIT Kharagpur',
  'IIT Hyderabad', 'IIT Roorkee', 'IIT Guwahati', 'IIT BHU',
  'NIT Trichy', 'NIT Warangal', 'NIT Surathkal', 'NIT Calicut', 'NIT Rourkela',
  'BITS Pilani', 'BITS Goa', 'BITS Hyderabad',
  'IIIT Hyderabad', 'IIIT Delhi', 'IIIT Bangalore',
  'VIT Vellore', 'Manipal Institute of Technology', 'SRM IST',
  'DTU Delhi', 'NSUT Delhi', 'IIIT Allahabad',
  'PEC Chandigarh', 'Jadavpur University', 'BIT Mesra',
  'Thapar University',
];

export function generateMockRecommendations(profile) {
  const colleges = [
    {
      college_id: 'iit-hyderabad',
      college_name: 'IIT Hyderabad',
      institute_type: 'IIT',
      state: 'Telangana',
      city: 'Hyderabad',
      zone: 'South',
      matched_branch: profile.preferred_branches?.[0] || 'Computer Science & Engineering',
      fit_bucket: 'safe',
      base_score: 0.92,
      hybrid_adjustment: 0.03,
      final_score: 0.95,
      score: 0.95,
      score_breakdown: { rank_score: 0.90, affordability_score: 0.85, location_score: 0.95, hostel_bonus: 0.10 },
      enrichment_status: 'pending',
      reasons: [
        'Rank comfortably within closing cutoff range',
        'Annual cost within budget at ₹4.5L/year',
        'Strong CSE program with AI/ML research focus',
        'Located in preferred zone — South',
      ],
      annual_cost_lakh: 4.5,
      hostel_available: true,
      official_source_urls: ['https://www.iith.ac.in/academics/'],
      enrichment: {
        fit_snapshot: {
          fit_bucket: 'safe',
          matched_branch: 'Computer Science & Engineering',
          rank_score: 0.90,
          closing_rank: 5200,
          fit_notes: ['Your rank of 4500 is well within the last 3-year closing rank of 5200', 'Strong fit for CSE branch allocation'],
        },
        cost_and_admissions: {
          annual_cost_lakh: 4.5,
          hostel_available: true,
          scholarship_notes: 'Merit-cum-means scholarships available for students with family income < 5 LPA',
          admission_process: 'JoSAA counselling based on JEE Advanced rank',
          counselling_body: 'JoSAA',
          official_source_url: 'https://www.iith.ac.in/admissions/',
        },
        outcomes_and_campus: {
          placement_summary: 'Median CTC ₹22 LPA, highest ₹1.2 Cr. 95% placement rate for CSE in 2024.',
          roi_indicator: 'High — tuition recovered within first year of placement',
          lab_facilities: 'State-of-the-art AI, Robotics, and VLSI labs',
          startup_culture: 'Active incubation center with 40+ student startups',
          extracurriculars: 'Annual tech fest (Elan & ηVision), 50+ clubs',
          attendance_policy: '75% minimum attendance required',
        },
      },
    },
    {
      college_id: 'nit-trichy',
      college_name: 'NIT Tiruchirappalli',
      institute_type: 'NIT',
      state: 'Tamil Nadu',
      city: 'Tiruchirappalli',
      zone: 'South',
      matched_branch: 'Computer Science & Engineering',
      fit_bucket: 'safe',
      base_score: 0.88,
      hybrid_adjustment: 0.02,
      final_score: 0.90,
      score: 0.90,
      score_breakdown: { rank_score: 0.85, affordability_score: 0.92, location_score: 0.88, hostel_bonus: 0.10 },
      enrichment_status: 'pending',
      reasons: [
        'Top NIT with excellent industry placements',
        'Very affordable at ₹2.8L/year',
        'Strong alumni network in tech companies',
      ],
      annual_cost_lakh: 2.8,
      hostel_available: true,
      official_source_urls: ['https://www.nitt.edu/'],
      enrichment: {
        fit_snapshot: {
          fit_bucket: 'safe',
          matched_branch: 'Computer Science & Engineering',
          rank_score: 0.85,
          closing_rank: 8500,
          fit_notes: ['Good rank margin for CSE — closing rank ~8500 in last round'],
        },
        cost_and_admissions: {
          annual_cost_lakh: 2.8,
          hostel_available: true,
          scholarship_notes: 'National-level scholarships accepted. Fee waivers for EWS/SC/ST categories.',
          admission_process: 'JoSAA counselling based on JEE Main rank',
          counselling_body: 'JoSAA',
          official_source_url: 'https://www.nitt.edu/home/admissions/',
        },
        outcomes_and_campus: {
          placement_summary: 'Median CTC ₹16 LPA for CSE. Top recruiters include Microsoft, Google, Amazon.',
          roi_indicator: 'Very High — one of the most affordable top-tier options',
          lab_facilities: 'Well-equipped computing labs, cloud infrastructure access',
          startup_culture: 'Growing ecosystem with annual hackathons',
          extracurriculars: 'Pragyan (tech fest), Festember (cultural fest), 60+ clubs',
          attendance_policy: '85% attendance required',
        },
      },
    },
    {
      college_id: 'bits-pilani',
      college_name: 'BITS Pilani',
      institute_type: 'Deemed University',
      state: 'Rajasthan',
      city: 'Pilani',
      zone: 'North',
      matched_branch: 'Computer Science & Engineering',
      fit_bucket: 'moderate',
      base_score: 0.82,
      hybrid_adjustment: 0.01,
      final_score: 0.83,
      score: 0.83,
      score_breakdown: { rank_score: 0.78, affordability_score: 0.60, location_score: 0.70, hostel_bonus: 0.10 },
      enrichment_status: 'pending',
      reasons: [
        'Excellent industry connections and PS-2 internship program',
        'Higher cost at ₹7.2L/year — near budget boundary',
        'Remote location but strong residential campus experience',
      ],
      annual_cost_lakh: 7.2,
      hostel_available: true,
      official_source_urls: ['https://www.bits-pilani.ac.in/'],
      enrichment: {
        fit_snapshot: {
          fit_bucket: 'moderate',
          matched_branch: 'Computer Science & Engineering',
          rank_score: 0.78,
          closing_rank: 350,
          fit_notes: ['BITSAT cutoff trending upward', 'Consider dual-degree options for better chances'],
        },
        cost_and_admissions: {
          annual_cost_lakh: 7.2,
          hostel_available: true,
          scholarship_notes: 'Merit scholarships available. Board-topper fee waivers.',
          admission_process: 'BITSAT examination — separate from JoSAA',
          counselling_body: 'BITS Admissions Division',
          official_source_url: 'https://www.bits-pilani.ac.in/admissions/',
        },
        outcomes_and_campus: {
          placement_summary: 'Median CTC ₹23 LPA. Strong presence in fintech, consulting, and product companies.',
          roi_indicator: 'Moderate — higher fees but strong salary outcomes',
          lab_facilities: 'Research-oriented labs, strong CS infrastructure',
          startup_culture: 'One of the strongest in India — multiple unicorn founders are alumni',
          extracurriculars: 'APOGEE (tech fest), Oasis (cultural), strong sports culture',
          attendance_policy: 'Flexible attendance policy',
        },
      },
    },
    {
      college_id: 'iiit-hyderabad',
      college_name: 'IIIT Hyderabad',
      institute_type: 'IIIT',
      state: 'Telangana',
      city: 'Hyderabad',
      zone: 'South',
      matched_branch: 'Computer Science & Engineering',
      fit_bucket: 'ambitious',
      base_score: 0.75,
      hybrid_adjustment: 0.04,
      final_score: 0.79,
      score: 0.79,
      score_breakdown: { rank_score: 0.65, affordability_score: 0.80, location_score: 0.95, hostel_bonus: 0.10 },
      enrichment_status: 'pending',
      reasons: [
        'Premier research institution for CS',
        'Competitive admission through UGEE',
        'Rank may be tight for direct CSE admission',
      ],
      annual_cost_lakh: 5.0,
      hostel_available: true,
      official_source_urls: ['https://www.iiit.ac.in/'],
      enrichment: {
        fit_snapshot: {
          fit_bucket: 'ambitious',
          matched_branch: 'Computer Science & Engineering',
          rank_score: 0.65,
          closing_rank: 3800,
          fit_notes: ['Your rank is at the edge — consider CLD or ECE as backup options', 'Evidence confidence: moderate'],
        },
        cost_and_admissions: {
          annual_cost_lakh: 5.0,
          hostel_available: true,
          scholarship_notes: 'Limited merit scholarships available',
          admission_process: 'UGEE (JEE Main based) + interview for some programs',
          counselling_body: 'IIIT Hyderabad Admissions',
          official_source_url: 'https://www.iiit.ac.in/admissions/',
        },
        outcomes_and_campus: {
          placement_summary: 'Median CTC ₹26 LPA for CSE. Known for research-to-industry pipeline.',
          roi_indicator: 'High — strong placements relative to fees',
          lab_facilities: 'Top-tier research labs in NLP, CV, Robotics',
          startup_culture: 'Strong — CIE incubator, research commercialization culture',
          extracurriculars: 'Felicity (annual festival), research clubs, competitive programming',
          attendance_policy: 'Project-based evaluation, moderate attendance rules',
        },
      },
    },
    {
      college_id: 'iit-bombay',
      college_name: 'IIT Bombay',
      institute_type: 'IIT',
      state: 'Maharashtra',
      city: 'Mumbai',
      zone: 'West',
      matched_branch: 'Computer Science & Engineering',
      fit_bucket: 'stretch',
      base_score: 0.68,
      hybrid_adjustment: 0.05,
      final_score: 0.73,
      score: 0.73,
      score_breakdown: { rank_score: 0.50, affordability_score: 0.88, location_score: 0.80, hostel_bonus: 0.10 },
      enrichment_status: 'pending',
      reasons: [
        'Top-ranked engineering institution in India',
        'CSE closing rank significantly lower than your rank',
        'Consider alternate branches for realistic admission chances',
      ],
      annual_cost_lakh: 4.8,
      hostel_available: true,
      official_source_urls: ['https://www.iitb.ac.in/'],
      enrichment: {
        fit_snapshot: {
          fit_bucket: 'stretch',
          matched_branch: 'Computer Science & Engineering',
          rank_score: 0.50,
          closing_rank: 120,
          fit_notes: ['CSE closing rank ~120 is far below your rank', 'Consider EE, Meta, or EP for realistic chances', 'Stretch pick — include only as an aspirational option'],
        },
        cost_and_admissions: {
          annual_cost_lakh: 4.8,
          hostel_available: true,
          scholarship_notes: 'MCM scholarships for income < 5 LPA. SC/ST full fee waiver.',
          admission_process: 'JoSAA counselling based on JEE Advanced rank',
          counselling_body: 'JoSAA',
          official_source_url: 'https://www.iitb.ac.in/newacadhome/JoSAA.jsp',
        },
        outcomes_and_campus: {
          placement_summary: 'Median CTC ₹28 LPA overall. CSE median above ₹40 LPA.',
          roi_indicator: 'Very High — brand value ensures strong ROI across all branches',
          lab_facilities: 'World-class facilities across all departments',
          startup_culture: 'SINE incubator, 100+ funded startups from campus',
          extracurriculars: 'Mood Indigo, Techfest (Asia\'s largest), 100+ clubs',
          attendance_policy: '80% attendance required for most departments',
        },
      },
    },
  ];

  return {
    request_id: 'demo-' + Date.now(),
    student_profile: profile,
    recommendations: colleges.slice(0, profile.max_results || 5),
    stage: 'enriched',
    filtered_out_count: 12,
    notes: [
      'Results sorted by composite score (rank fit + affordability + location + hostel)',
      'Public signals available on request for deeper student-perspective insights',
    ],
  };
}

export function generateMockExplore(collegeName) {
  return {
    request_id: 'explore-' + Date.now(),
    college_name: collegeName,
    college_id: collegeName.toLowerCase().replace(/\s/g, '-'),
    enrichment_status: 'hydrated',
    official_summary: `${collegeName} is one of India's premier engineering institutions, offering a rigorous academic curriculum with strong emphasis on research and innovation. The institute admits students through nationally recognized entrance examinations and provides comprehensive hostel facilities for all admitted students. With a focus on cutting-edge research and industry collaboration, the institution maintains high academic standards and produces graduates who are highly sought after by top employers in India and abroad.`,
    citations: [
      {
        chunk_id: 'c_001',
        title: `${collegeName} — Official Admissions Page`,
        url: 'https://example.edu/admissions/',
        supporting_text: 'Admission to B.Tech programs is through JoSAA counselling based on JEE Advanced rank. The institute offers 10 undergraduate programs across engineering and science disciplines.',
      },
      {
        chunk_id: 'c_002',
        title: `${collegeName} — Placement Statistics 2024`,
        url: 'https://example.edu/placements/',
        supporting_text: 'The 2024 placement season saw 95% of registered students placed with a median CTC of ₹22 LPA. Top recruiters included Microsoft, Google, Goldman Sachs, and McKinsey.',
      },
    ],
    official_sources: [
      {
        title: 'Official Admissions Page',
        url: 'https://example.edu/admissions/',
        snippet: 'Comprehensive admissions information including eligibility, process, and important dates.',
        trust_label: 'official_verified',
      },
      {
        title: 'Placement Report 2024',
        url: 'https://example.edu/placements/',
        snippet: 'Annual placement statistics and recruiter information.',
        trust_label: 'official_verified',
      },
    ],
    enrichment: {
      fit_snapshot: null,
      cost_and_admissions: {
        annual_cost_lakh: 4.5,
        hostel_available: true,
        scholarship_notes: 'Merit-cum-means scholarships available. Fee waiver for economically disadvantaged students.',
        admission_process: 'JoSAA counselling based on JEE Advanced rank',
        counselling_body: 'JoSAA',
        official_source_url: 'https://example.edu/admissions/',
      },
      outcomes_and_campus: {
        placement_summary: 'Median CTC ₹22 LPA, highest ₹1.2 Cr. Strong presence of tech, consulting, and finance recruiters.',
        roi_indicator: 'High',
        lab_facilities: 'State-of-the-art research labs across all departments',
        startup_culture: 'Active incubation center supporting student entrepreneurship',
        extracurriculars: 'Annual tech and cultural festivals, 50+ student clubs',
        attendance_policy: '75% minimum attendance required',
      },
    },
    public_signals_disclaimer: 'The signals below are sourced from Reddit and YouTube — crowdsourced, unverified, and may include promotional or exaggerated claims. Treat as directional only. Official institute sources take precedence.',
    public_signals_report: null,
    warnings: [],
  };
}
